FROM debian:stable

MAINTAINER Alexandr Shurigin <alexandr.shurigin@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade -y

USER root

EXPOSE 80

ADD scripts/ /

WORKDIR /app/code/

VOLUME /app/code/

RUN chmod +x /*.sh && /cleanup.sh